# ----------------------------------------------------------------------------------------------------
# NHÂN VIÊN GIAO DỊCH
# ----------------------------------------------------------------------------------------------------


### Register

POST http://127.0.0.1:8000/register
Content-Type: application/json

{
    "username": "manager01",
    "password": "123456",
    "role": "1"
}
### Login

POST http://127.0.0.1:8000/login
Content-Type: application/json

{"username": "employee82", "password": "123456"}

### Logout

POST http://127.0.0.1:8000/logout
Content-Type: application/json
Authorization: Token 877dc3520735d130169f41e876a0cdd4ff686f72

{}

### create shipment

POST http://127.0.0.1:8000/Transaction/create_shipment
Content-Type: application/json
Authorization: Token 877dc3520735d130169f41e876a0cdd4ff686f72

{
    "des": 30,
    "sender_name": "Alan",
    "sender_address": "fjwejfiwejfj",
    "sender_postal_code": "HHHHH12345",
    "sender_total_payment": 15,
    "sender_phone": 19001008,
    "receiver_address": "New York",
    "receiver_postal_code": "HHHHH12346",
    "receiver_name": "John Smith",
    "receiver_phone": "482938428",
    "receiver_total_payment": 0,
    "receiving_date": "2023-12-25",
    "good_type": "HH",
    "special_service": "",
    "weight": 20
}


### create_transaction_to_consolidation_point

POST http://127.0.0.1:8000/Transaction/transaction_employee/shipment_to_consolidation
Content-Type: application/json
Authorization: Token 877dc3520735d130169f41e876a0cdd4ff686f72

{
    "shipment_id": 5  
}

### confirm shipment from consolidation point
POST http://127.0.0.1:8000/Transaction/transaction_employee/shipment_from_consolidation
Content-Type: application/json
Authorization: Token 5fcef48720e0fafae95818d05c7c38d16761b471

{
    "transaction_id": [12]
}

### create transaction to receiver
POST http://127.0.0.1:8000/Transaction/transaction_employee/create_transaction_to_receiver
Content-Type: application/json
Authorization: Token 5fcef48720e0fafae95818d05c7c38d16761b471

{
    "shipment_id": 5
}

### confirm success customer transaction
POST http://127.0.0.1:8000/Transaction/transaction_employee/confirm_complete_shipment
Content-Type: application/json
Authorization: Token 5fcef48720e0fafae95818d05c7c38d16761b471

{
    "customer_transaction_id": [1]
}


### confirm failed customer transaction
POST http://127.0.0.1:8000/Transaction/transaction_employee/confirm_failed_shipment_and_send_back
Content-Type: application/json
Authorization: Token 5fcef48720e0fafae95818d05c7c38d16761b471

{
    "customer_transaction_id": [1]
}

### statistic failed, completed shipment
GET http://127.0.0.1:8000/Transaction/transaction_employee/list_complete_and_fail_shipment
Content-Type: application/json
Authorization: Token 5fcef48720e0fafae95818d05c7c38d16761b471


# ----------------------------------------------------------------------------------------------------
# NHÂN VIÊN TẬP KẾT
# ----------------------------------------------------------------------------------------------------

### confirm_shipment_from_transaction_department
POST http://127.0.0.1:8000/Transaction/consolidation_employee/shipment_from_transaction
Content-Type: application/json
Authorization: Token b3219d00ae92b7bfc17cf3fd2321dddcda053b2b

{
    "transaction_id": [10]
}

### create transaction to target consolidation point
POST http://127.0.0.1:8000/Transaction/consolidation_employee/shipment_to_consolidation
Content-Type: application/json
Authorization: Token b3219d00ae92b7bfc17cf3fd2321dddcda053b2b

{
    "shipment_id": 5
}

### confirm transaction from other consolidation point
POST http://127.0.0.1:8000/Transaction/consolidation_employee/shipment_from_consolidation
Content-Type: application/json
Authorization: Token d7e89cd0c62b8b8d901fb6f72fd616772323653a

{
    "transaction_id": [11]
}

### Create transaction to correspond transaction point
POST http://127.0.0.1:8000/Transaction/consolidation_employee/shipment_to_transaction
Content-Type: application/json
Authorization: Token 93139181e2eae9a2f92cc6454a30591a94078ccf

{
    "shipment_id": 5
}


## Khách hàng

### search_shipment
GET http://127.0.0.1:8000/Transaction/search_shipment
Content-Type: application/json

{
    "code": "662be96f9aa34d1"
}

## Truong diem giao dich, tap ket

### list_shipment
GET http://127.0.0.1:8000/Transaction/manager/list_shipment
Content-Type: application/json
Authorization: Token a8617bdeae22488cdce6860fa42b2fba402cfdff

## Lãnh đạo

### list_department
GET http://127.0.0.1:8000/Transaction/list_department
Content-Type: application/json
Authorization: Token 62db23a728621431acd7df44ba712bbb677af26a

### list_manager
GET http://127.0.0.1:8000/Transaction/list_manager
Content-Type: application/json
Authorization: Token 62db23a728621431acd7df44ba712bbb677af26a

### shipment_statistic
GET http://127.0.0.1:8000/Transaction/shipment_statistic
Content-Type: application/json
Authorization: Token 62db23a728621431acd7df44ba712bbb677af26a