# Generated by Django 4.2.7 on 2023-11-15 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ConsolidationPoint",
            fields=[
                ("department_id", models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name="TransactionPoint",
            fields=[
                ("department_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "consolidation_point",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Account.consolidationpoint",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="consolidationpoint",
            name="transaction_points",
            field=models.ManyToManyField(to="Account.transactionpoint"),
        ),
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=50)),
                ("password", models.CharField(max_length=50)),
                (
                    "role",
                    models.CharField(
                        choices=[("2", "Leader"), ("1", "Manager"), ("0", "Employee")],
                        default="0",
                        max_length=50,
                    ),
                ),
                (
                    "consolidation_point",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Account.consolidationpoint",
                    ),
                ),
                (
                    "transaction_point",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Account.transactionpoint",
                    ),
                ),
            ],
        ),
    ]
