# Generated by Django 4.2.7 on 2023-11-14 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0002_remove_transaction_des_remove_transaction_pos_and_more'),
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=15)),
                ('code', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Giao_dich',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('0', 'Noi giao dich cua nguoi gui.'), ('1', 'Noi tap ket.'), ('2', 'Noi giao dich cua nguoi nhan.'), ('3', 'Da den tay nguoi nhan.')], default='0', max_length=50)),
                ('sender_address', models.CharField(max_length=100)),
                ('sender_postal_code', models.CharField(max_length=10)),
                ('sender_total_payment', models.DecimalField(decimal_places=2, max_digits=12)),
                ('receiver_address', models.CharField(max_length=100)),
                ('receiver_postal_code', models.CharField(max_length=10)),
                ('receiver_name', models.CharField(max_length=30)),
                ('receiver_phone', models.CharField(max_length=15)),
                ('receiver_total_payment', models.DecimalField(decimal_places=2, max_digits=12)),
                ('DHCode', models.CharField(max_length=5, null=True)),
                ('receiving_date', models.DateField(blank=True, null=True)),
                ('good_type', models.CharField(choices=[('TL', 'tai lieu'), ('HH', 'hang hoa')], default='HH', max_length=8)),
                ('special_service', models.CharField(max_length=50, null=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=4)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Tap_ket',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='account',
            name='department',
        ),
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('LD', 'lanh_dao'), ('TTK', 'truong_tap_ket'), ('TGD', 'truong_giao_dich'), ('NV', 'nhan_vien'), ('KH', 'khach_hang')], default='NV', max_length=50),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.AddField(
            model_name='tap_ket',
            name='manager_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Account.account'),
        ),
        migrations.AddField(
            model_name='giao_dich',
            name='manager_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Account.account'),
        ),
        migrations.AddField(
            model_name='giao_dich',
            name='tap_ket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Account.tap_ket'),
        ),
    ]
