# Generated by Django 3.2.5 on 2023-11-25 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('shipment_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Pending', max_length=50)),
                ('sender_address', models.CharField(default=None, max_length=100, null=True)),
                ('sender_postal_code', models.CharField(default=None, max_length=10, null=True)),
                ('sender_total_payment', models.DecimalField(decimal_places=2, default=None, max_digits=12, null=True)),
                ('receiver_address', models.CharField(default=None, max_length=100, null=True)),
                ('receiver_postal_code', models.CharField(default=None, max_length=10, null=True)),
                ('receiver_name', models.CharField(default=None, max_length=30, null=True)),
                ('receiver_phone', models.CharField(default=None, max_length=15, null=True)),
                ('receiver_total_payment', models.DecimalField(decimal_places=2, default=None, max_digits=12, null=True)),
                ('DHCode', models.CharField(default=None, max_length=5, null=True)),
                ('receiving_date', models.DateField(blank=True, default=None, null=True)),
                ('good_type', models.CharField(choices=[('TL', 'tai lieu'), ('HH', 'hang hoa')], default='HH', max_length=8)),
                ('special_service', models.CharField(default=None, max_length=50, null=True)),
                ('weight', models.DecimalField(decimal_places=2, default=None, max_digits=4, null=True)),
                ('current_pos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_current_pos', to='Account.department')),
                ('pos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_pos', to='Account.department')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Pending', max_length=50)),
                ('des', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_des', to='Account.department')),
                ('pos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_pos', to='Account.department')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Transaction.shipment')),
            ],
        ),
    ]
