# Generated by Django 4.2.7 on 2023-11-21 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
        ('Transaction', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='progress',
        ),
        migrations.AddField(
            model_name='shipment',
            name='DHCode',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='good_type',
            field=models.CharField(choices=[('TL', 'tai lieu'), ('HH', 'hang hoa')], default='HH', max_length=8),
        ),
        migrations.AddField(
            model_name='shipment',
            name='pos',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='shipment_pos', to='Account.department'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='receiver_address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='receiver_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='receiver_phone',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='receiver_postal_code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='receiver_total_payment',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='receiving_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='sender_address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='sender_postal_code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='sender_total_payment',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='special_service',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
    ]
