# Generated by Django 4.2.7 on 2023-11-14 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='des',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='pos',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='shipment',
        ),
        migrations.DeleteModel(
            name='Shipment',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
