# Generated by Django 5.0 on 2023-12-14 09:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='DHCode',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
