# Generated by Django 4.2.7 on 2023-11-21 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0002_remove_shipment_progress_shipment_dhcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='DHCode',
            field=models.CharField(default=None, max_length=5),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='receiver_address',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='receiver_name',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='receiver_phone',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='receiver_postal_code',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='receiver_total_payment',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=12),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='receiving_date',
            field=models.DateField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='sender_address',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='sender_postal_code',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='sender_total_payment',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=12),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='special_service',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=4),
        ),
    ]
