# Generated by Django 5.0 on 2023-12-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0002_transaction_created_at_alter_shipment_dhcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='DHCode',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='special_service',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
