# Generated by Django 4.2.7 on 2023-11-21 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0003_alter_shipment_dhcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='DHCode',
            field=models.CharField(default=None, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='receiver_address',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='receiver_name',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='receiver_phone',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='receiver_postal_code',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='receiver_total_payment',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='receiving_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='sender_address',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='sender_postal_code',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='sender_total_payment',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='special_service',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=4, null=True),
        ),
    ]
