# Generated by Django 5.0 on 2023-12-14 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0003_alter_shipment_dhcode_alter_shipment_special_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='DHCode',
            field=models.CharField(blank=True, default=None, max_length=15, null=True),
        ),
    ]
