# Generated by Django 5.0 on 2023-12-15 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_alter_user_department'),
        ('Transaction', '0004_alter_shipment_dhcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='des',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipment_des', to='Account.department'),
        ),
    ]
