# Generated by Django 5.0 on 2023-12-15 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_alter_user_department'),
        ('Transaction', '0005_shipment_des'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='des',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_des', to='Account.department'),
        ),
    ]
