# Generated by Django 4.2.7 on 2023-11-21 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0005_alter_shipment_dhcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='DHCode',
            field=models.CharField(default=None, max_length=5, null=True),
        ),
    ]
