# Generated by Django 5.0 on 2023-12-24 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0007_shipment_sender_phone_customertransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='sender_name',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
    ]
