# Generated by Django 4.2.7 on 2023-11-21 09:21

from django.db import migrations, models
import django.db.models.deletion

def set_default_current_pos(apps, schema_editor):
    Shipment = apps.get_model('Transaction', 'Shipment')
    Department = apps.get_model('Account', 'Department')  # Replace 'account' with the actual app name

    default_department = Department.objects.get(department_id=1)  # Replace with your conditions

    for shipment in Shipment.objects.filter(current_pos=None):
        shipment.current_pos = default_department
        shipment.save()

class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_remove_user_department'),
        ('Transaction', '0010_alter_shipment_current_pos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='current_pos',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shipment_current_pos', to='Account.department'),
        ),
        migrations.RunPython(set_default_current_pos),
    ]
