# Generated by Django 4.2.7 on 2023-12-26 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0010_shipment_shipment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True),
        ),
    ]
