# Generated by Django 4.2.7 on 2023-11-21 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0013_alter_shipment_current_pos'),
    ]

    operations = [
    ]
