# Generated by Django 4.2.7 on 2023-11-21 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0014_auto_20231121_1648'),
    ]

    operations = [
    ]
