# Generated by Django 4.2.7 on 2023-11-21 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0016_alter_shipment_current_pos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='current_pos',
        ),
    ]
